# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 694)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Graphicloads-Colorful-Long-Shadow-Car.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, 20)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formFrame = QtWidgets.QFrame(self.horizontalFrame)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinSilindir = QtWidgets.QSpinBox(self.formFrame)
        self.spinSilindir.setObjectName("spinSilindir")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinSilindir)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textMotorHacmi = QtWidgets.QTextEdit(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textMotorHacmi.sizePolicy().hasHeightForWidth())
        self.textMotorHacmi.setSizePolicy(sizePolicy)
        self.textMotorHacmi.setMinimumSize(QtCore.QSize(0, 10))
        self.textMotorHacmi.setObjectName("textMotorHacmi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textMotorHacmi)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textBeygir = QtWidgets.QTextEdit(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBeygir.sizePolicy().hasHeightForWidth())
        self.textBeygir.setSizePolicy(sizePolicy)
        self.textBeygir.setMinimumSize(QtCore.QSize(0, 10))
        self.textBeygir.setObjectName("textBeygir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBeygir)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.textAgirlik = QtWidgets.QTextEdit(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textAgirlik.sizePolicy().hasHeightForWidth())
        self.textAgirlik.setSizePolicy(sizePolicy)
        self.textAgirlik.setMinimumSize(QtCore.QSize(0, 10))
        self.textAgirlik.setObjectName("textAgirlik")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textAgirlik)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinIvme = QtWidgets.QSpinBox(self.formFrame)
        self.spinIvme.setObjectName("spinIvme")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinIvme)
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.textYil = QtWidgets.QTextEdit(self.formFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textYil.sizePolicy().hasHeightForWidth())
        self.textYil.setSizePolicy(sizePolicy)
        self.textYil.setMinimumSize(QtCore.QSize(0, 10))
        self.textYil.setObjectName("textYil")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textYil)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboOrigin = QtWidgets.QComboBox(self.formFrame)
        self.comboOrigin.setObjectName("comboOrigin")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboOrigin)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboMarka = QtWidgets.QComboBox(self.formFrame)
        self.comboMarka.setObjectName("comboMarka")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboMarka)
        self.horizontalLayout_2.addWidget(self.formFrame)
        self.horizontalLayout_4.addWidget(self.horizontalFrame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(54, 3, 0, 12)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButtonHesapla = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHesapla.setMinimumSize(QtCore.QSize(200, 75))
        self.pushButtonHesapla.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButtonHesapla.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/robot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHesapla.setIcon(icon1)
        self.pushButtonHesapla.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonHesapla.setShortcut("")
        self.pushButtonHesapla.setCheckable(False)
        self.pushButtonHesapla.setAutoDefault(False)
        self.pushButtonHesapla.setDefault(False)
        self.pushButtonHesapla.setFlat(False)
        self.pushButtonHesapla.setObjectName("pushButtonHesapla")
        self.horizontalLayout_3.addWidget(self.pushButtonHesapla)
        self.checkBoxModel = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxModel.setObjectName("checkBoxModel")
        self.horizontalLayout_3.addWidget(self.checkBoxModel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.labelSonuc = QtWidgets.QLabel(self.centralwidget)
        self.labelSonuc.setMinimumSize(QtCore.QSize(0, 100))
        self.labelSonuc.setText("")
        self.labelSonuc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSonuc.setObjectName("labelSonuc")
        self.verticalLayout_2.addWidget(self.labelSonuc)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FuelEstimator © Berk Kılıçoğlu"))
        self.label.setText(_translate("MainWindow", "Silindir Sayısı"))
        self.label_2.setText(_translate("MainWindow", "Motor Hacmi"))
        self.label_3.setText(_translate("MainWindow", "Beygir Gücü"))
        self.label_4.setText(_translate("MainWindow", "Araç Ağırlığı"))
        self.label_5.setText(_translate("MainWindow", "İvmelenme Süresi"))
        self.label_6.setText(_translate("MainWindow", "Model Yıl"))
        self.label_7.setText(_translate("MainWindow", "Origin"))
        self.label_8.setText(_translate("MainWindow", "Marka"))
        self.pushButtonHesapla.setToolTip(_translate("MainWindow", "Click..Gradient Boosting Regression Estimator"))
        self.pushButtonHesapla.setText(_translate("MainWindow", "HESAPLA"))
        self.checkBoxModel.setText(_translate("MainWindow", "Model Dump"))

import icons_rc
